FROM alpine:latest

RUN apk --no-cache update
RUN apk add --no-cache apache2

WORKDIR /var/www/localhost/htdocs
COPY  /page/index.html  /var/www/localhost/htdocs 
RUN echo 'Hello Amazing DevOps World!' > /var/www/localhost/htdocs

CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]

EXPOSE 80